import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 28, fontSize: 11, fontFamily: 'Helvetica' },
  title: { fontSize: 18, marginBottom: 12, fontWeight: 700 },
  section: { marginBottom: 8 },
  row: { marginBottom: 4 },
  label: { fontSize: 9, color: '#555' },
  val: { fontSize: 11 },
  footer: { position: 'absolute', bottom: 12, left: 0, right: 0, textAlign: 'center', fontSize: 9, color: '#666' },
  imgPage: { padding: 16 },
  imgWrapper: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  img: { width: '100%', height: '100%', objectFit: 'contain' }
})

interface PayablePDFProps {
  payable: {
    vendorName: string
    location?: { stationName?: string }
    paymentMethod: string
    amount: number
    notes: string
    createdAt: string
    images: string[]
  }
  imageDataUris: string[]
}

const fmtMoney = (v: number) => `$${Number(v || 0).toFixed(2)}`

export default function PayablePDF({ payable, imageDataUris }: PayablePDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Payable Summary</Text>
        <View style={styles.section}>
          <View style={styles.row}>
            <Text style={styles.label}>Vendor</Text>
            <Text style={styles.val}>{payable.vendorName || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Location</Text>
            <Text style={styles.val}>{payable.location?.stationName || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Payment Method</Text>
            <Text style={styles.val}>{payable.paymentMethod || '-'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Amount</Text>
            <Text style={styles.val}>{fmtMoney(payable.amount)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Created</Text>
            <Text style={styles.val}>{new Date(payable.createdAt).toLocaleString()}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Notes</Text>
            <Text style={styles.val}>{payable.notes || '-'}</Text>
          </View>
        </View>
        <Text style={styles.footer}>Generated by The Hub</Text>
      </Page>
      {imageDataUris.map((src, i) => (
        <Page key={i} size="A4" style={styles.imgPage}>
          <View style={styles.imgWrapper}>
            {src ? <Image style={styles.img} src={src} /> : <Text>Image unavailable</Text>}
          </View>
          <Text style={styles.footer}>Attachment {i + 1} of {imageDataUris.length}</Text>
        </Page>
      ))}
    </Document>
  )
}