services:
  mongo:
    container_name: mongo
    image: mongo:8
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - UPLOAD_SERVICE_URL=http://cdn:5001
    depends_on:
      - mongo
    restart: always

  cdn:
    container_name: cdn
    build: ./cdn
    volumes:
      - uploads:/app/uploads
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_DOCKER=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - cdn
    restart: no

volumes:
  dist:
  uploads:
  mongodb_data:
