services:
  mongo:
    container_name: mongo
    image: mongo:8
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always
  redis:
    container_name: redis
    image: redis:7
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - UPLOAD_SERVICE_URL=http://cdn:5001
      - REDIS_URL=redis://redis:6379
      - FORCE_COLOR=1
    depends_on:
      - mongo
      - redis
    restart: always

  cdn:
    container_name: cdn
    build: ./cdn
    volumes:
      - uploads:/app/uploads
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    restart: always

  # signaling:
  #   container_name: signaling
  #   build:
  #     context: ./signaling
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "5002:5002"
  #   restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_DOCKER=true
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
      - cdn
    restart: on-failure:3

volumes:
  dist:
  uploads:
  mongodb_data:
  backend_node_modules:
  frontend_node_modules:
