/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NavbarLayoutRouteImport } from './routes/_navbarLayout'
import { Route as NavbarLayoutIndexRouteImport } from './routes/_navbarLayout/index'
import { Route as NavbarLayoutVendorRouteImport } from './routes/_navbarLayout/vendor'
import { Route as NavbarLayoutStatusRouteImport } from './routes/_navbarLayout/status'
import { Route as NavbarLayoutSettingsRouteImport } from './routes/_navbarLayout/settings'
import { Route as NavbarLayoutReportsRouteImport } from './routes/_navbarLayout/reports'
import { Route as NavbarLayoutPoRouteImport } from './routes/_navbarLayout/po'
import { Route as NavbarLayoutPayablesRouteImport } from './routes/_navbarLayout/payables'
import { Route as NavbarLayoutOrderRecRouteImport } from './routes/_navbarLayout/order-rec'
import { Route as NavbarLayoutKardpollRouteImport } from './routes/_navbarLayout/kardpoll'
import { Route as NavbarLayoutFleetRouteImport } from './routes/_navbarLayout/fleet'
import { Route as NavbarLayoutDailyReportsRouteImport } from './routes/_navbarLayout/daily-reports'
import { Route as NavbarLayoutCycleCountRouteImport } from './routes/_navbarLayout/cycle-count'
import { Route as NavbarLayoutAuditRouteImport } from './routes/_navbarLayout/audit'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as NavbarLayoutVendorIndexRouteImport } from './routes/_navbarLayout/vendor/index'
import { Route as NavbarLayoutStatusIndexRouteImport } from './routes/_navbarLayout/status/index'
import { Route as NavbarLayoutSettingsIndexRouteImport } from './routes/_navbarLayout/settings/index'
import { Route as NavbarLayoutPoIndexRouteImport } from './routes/_navbarLayout/po/index'
import { Route as NavbarLayoutPayablesIndexRouteImport } from './routes/_navbarLayout/payables/index'
import { Route as NavbarLayoutOrderRecIndexRouteImport } from './routes/_navbarLayout/order-rec/index'
import { Route as NavbarLayoutKardpollIndexRouteImport } from './routes/_navbarLayout/kardpoll/index'
import { Route as NavbarLayoutFleetIndexRouteImport } from './routes/_navbarLayout/fleet/index'
import { Route as NavbarLayoutCycleCountIndexRouteImport } from './routes/_navbarLayout/cycle-count/index'
import { Route as NavbarLayoutAuditIndexRouteImport } from './routes/_navbarLayout/audit/index'
import { Route as NavbarLayoutVendorListRouteImport } from './routes/_navbarLayout/vendor/list'
import { Route as NavbarLayoutStatusListRouteImport } from './routes/_navbarLayout/status/list'
import { Route as NavbarLayoutSettingsUsersRouteImport } from './routes/_navbarLayout/settings/users'
import { Route as NavbarLayoutSettingsPaypointsRouteImport } from './routes/_navbarLayout/settings/paypoints'
import { Route as NavbarLayoutReportsSalesSummaryRouteImport } from './routes/_navbarLayout/reports/sales-summary'
import { Route as NavbarLayoutReportsOtherRouteImport } from './routes/_navbarLayout/reports/other'
import { Route as NavbarLayoutPoSignatureRouteImport } from './routes/_navbarLayout/po/signature'
import { Route as NavbarLayoutPoReceiptRouteImport } from './routes/_navbarLayout/po/receipt'
import { Route as NavbarLayoutPoListRouteImport } from './routes/_navbarLayout/po/list'
import { Route as NavbarLayoutPayablesReviewRouteImport } from './routes/_navbarLayout/payables/review'
import { Route as NavbarLayoutPayablesListRouteImport } from './routes/_navbarLayout/payables/list'
import { Route as NavbarLayoutPayablesImagesRouteImport } from './routes/_navbarLayout/payables/images'
import { Route as NavbarLayoutOrderRecListRouteImport } from './routes/_navbarLayout/order-rec/list'
import { Route as NavbarLayoutOrderRecDashboardRouteImport } from './routes/_navbarLayout/order-rec/dashboard'
import { Route as NavbarLayoutOrderRecIdRouteImport } from './routes/_navbarLayout/order-rec/$id'
import { Route as NavbarLayoutKardpollListRouteImport } from './routes/_navbarLayout/kardpoll/list'
import { Route as NavbarLayoutFleetListRouteImport } from './routes/_navbarLayout/fleet/list'
import { Route as NavbarLayoutDailyReportsShiftWorksheetRouteImport } from './routes/_navbarLayout/daily-reports/shift-worksheet'
import { Route as NavbarLayoutDailyReportsCashSummaryRouteImport } from './routes/_navbarLayout/daily-reports/cash-summary'
import { Route as NavbarLayoutCycleCountListRouteImport } from './routes/_navbarLayout/cycle-count/list'
import { Route as NavbarLayoutAuditTemplatesRouteImport } from './routes/_navbarLayout/audit/templates'
import { Route as NavbarLayoutAuditChecklistRouteImport } from './routes/_navbarLayout/audit/checklist'
import { Route as NavbarLayoutSettingsUsersIndexRouteImport } from './routes/_navbarLayout/settings/users/index'
import { Route as NavbarLayoutSettingsPermissionsIndexRouteImport } from './routes/_navbarLayout/settings/permissions/index'
import { Route as NavbarLayoutSettingsPaypointsIndexRouteImport } from './routes/_navbarLayout/settings/paypoints/index'
import { Route as NavbarLayoutReportsSalesSummaryIndexRouteImport } from './routes/_navbarLayout/reports/sales-summary/index'
import { Route as NavbarLayoutDailyReportsShiftWorksheetIndexRouteImport } from './routes/_navbarLayout/daily-reports/shift-worksheet/index'
import { Route as NavbarLayoutAuditChecklistIndexRouteImport } from './routes/_navbarLayout/audit/checklist/index'
import { Route as NavbarLayoutVendorEditIdRouteImport } from './routes/_navbarLayout/vendor/edit/$id'
import { Route as NavbarLayoutSettingsUsersUserIdRouteImport } from './routes/_navbarLayout/settings/users/$userId'
import { Route as NavbarLayoutSettingsPaypointsSiteRouteImport } from './routes/_navbarLayout/settings/paypoints/$site'
import { Route as NavbarLayoutReportsSalesSummaryUploadRouteImport } from './routes/_navbarLayout/reports/sales-summary/upload'
import { Route as NavbarLayoutDailyReportsShiftWorksheetCreateRouteImport } from './routes/_navbarLayout/daily-reports/shift-worksheet/create'
import { Route as NavbarLayoutDailyReportsShiftWorksheetWorksheetRouteImport } from './routes/_navbarLayout/daily-reports/shift-worksheet/$worksheet'
import { Route as NavbarLayoutCycleCountEntryIdRouteImport } from './routes/_navbarLayout/cycle-count/entry/$id'
import { Route as NavbarLayoutAuditTemplatesSelectRouteImport } from './routes/_navbarLayout/audit/templates/select'
import { Route as NavbarLayoutAuditTemplatesChecklistRouteImport } from './routes/_navbarLayout/audit/templates/checklist'
import { Route as NavbarLayoutAuditChecklistIdRouteImport } from './routes/_navbarLayout/audit/checklist/$id'
import { Route as NavbarLayoutAuditTemplatesSelectIndexRouteImport } from './routes/_navbarLayout/audit/templates/select/index'
import { Route as NavbarLayoutAuditTemplatesChecklistIndexRouteImport } from './routes/_navbarLayout/audit/templates/checklist/index'
import { Route as NavbarLayoutAuditTemplatesSelectListRouteImport } from './routes/_navbarLayout/audit/templates/select/list'
import { Route as NavbarLayoutAuditTemplatesSelectIdRouteImport } from './routes/_navbarLayout/audit/templates/select/$id'
import { Route as NavbarLayoutAuditTemplatesChecklistListRouteImport } from './routes/_navbarLayout/audit/templates/checklist/list'
import { Route as NavbarLayoutAuditTemplatesChecklistIdRouteImport } from './routes/_navbarLayout/audit/templates/checklist/$id'

const NavbarLayoutRoute = NavbarLayoutRouteImport.update({
  id: '/_navbarLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarLayoutIndexRoute = NavbarLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutVendorRoute = NavbarLayoutVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutStatusRoute = NavbarLayoutStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutSettingsRoute = NavbarLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutReportsRoute = NavbarLayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutPoRoute = NavbarLayoutPoRouteImport.update({
  id: '/po',
  path: '/po',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutPayablesRoute = NavbarLayoutPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutOrderRecRoute = NavbarLayoutOrderRecRouteImport.update({
  id: '/order-rec',
  path: '/order-rec',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutKardpollRoute = NavbarLayoutKardpollRouteImport.update({
  id: '/kardpoll',
  path: '/kardpoll',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutFleetRoute = NavbarLayoutFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutDailyReportsRoute =
  NavbarLayoutDailyReportsRouteImport.update({
    id: '/daily-reports',
    path: '/daily-reports',
    getParentRoute: () => NavbarLayoutRoute,
  } as any)
const NavbarLayoutCycleCountRoute = NavbarLayoutCycleCountRouteImport.update({
  id: '/cycle-count',
  path: '/cycle-count',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutAuditRoute = NavbarLayoutAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarLayoutVendorIndexRoute = NavbarLayoutVendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarLayoutVendorRoute,
} as any)
const NavbarLayoutStatusIndexRoute = NavbarLayoutStatusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarLayoutStatusRoute,
} as any)
const NavbarLayoutSettingsIndexRoute =
  NavbarLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutSettingsRoute,
  } as any)
const NavbarLayoutPoIndexRoute = NavbarLayoutPoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarLayoutPoRoute,
} as any)
const NavbarLayoutPayablesIndexRoute =
  NavbarLayoutPayablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutPayablesRoute,
  } as any)
const NavbarLayoutOrderRecIndexRoute =
  NavbarLayoutOrderRecIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutOrderRecRoute,
  } as any)
const NavbarLayoutKardpollIndexRoute =
  NavbarLayoutKardpollIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutKardpollRoute,
  } as any)
const NavbarLayoutFleetIndexRoute = NavbarLayoutFleetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarLayoutFleetRoute,
} as any)
const NavbarLayoutCycleCountIndexRoute =
  NavbarLayoutCycleCountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutCycleCountRoute,
  } as any)
const NavbarLayoutAuditIndexRoute = NavbarLayoutAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarLayoutAuditRoute,
} as any)
const NavbarLayoutVendorListRoute = NavbarLayoutVendorListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => NavbarLayoutVendorRoute,
} as any)
const NavbarLayoutStatusListRoute = NavbarLayoutStatusListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => NavbarLayoutStatusRoute,
} as any)
const NavbarLayoutSettingsUsersRoute =
  NavbarLayoutSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => NavbarLayoutSettingsRoute,
  } as any)
const NavbarLayoutSettingsPaypointsRoute =
  NavbarLayoutSettingsPaypointsRouteImport.update({
    id: '/paypoints',
    path: '/paypoints',
    getParentRoute: () => NavbarLayoutSettingsRoute,
  } as any)
const NavbarLayoutReportsSalesSummaryRoute =
  NavbarLayoutReportsSalesSummaryRouteImport.update({
    id: '/sales-summary',
    path: '/sales-summary',
    getParentRoute: () => NavbarLayoutReportsRoute,
  } as any)
const NavbarLayoutReportsOtherRoute =
  NavbarLayoutReportsOtherRouteImport.update({
    id: '/other',
    path: '/other',
    getParentRoute: () => NavbarLayoutReportsRoute,
  } as any)
const NavbarLayoutPoSignatureRoute = NavbarLayoutPoSignatureRouteImport.update({
  id: '/signature',
  path: '/signature',
  getParentRoute: () => NavbarLayoutPoRoute,
} as any)
const NavbarLayoutPoReceiptRoute = NavbarLayoutPoReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => NavbarLayoutPoRoute,
} as any)
const NavbarLayoutPoListRoute = NavbarLayoutPoListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => NavbarLayoutPoRoute,
} as any)
const NavbarLayoutPayablesReviewRoute =
  NavbarLayoutPayablesReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => NavbarLayoutPayablesRoute,
  } as any)
const NavbarLayoutPayablesListRoute =
  NavbarLayoutPayablesListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => NavbarLayoutPayablesRoute,
  } as any)
const NavbarLayoutPayablesImagesRoute =
  NavbarLayoutPayablesImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => NavbarLayoutPayablesRoute,
  } as any)
const NavbarLayoutOrderRecListRoute =
  NavbarLayoutOrderRecListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => NavbarLayoutOrderRecRoute,
  } as any)
const NavbarLayoutOrderRecDashboardRoute =
  NavbarLayoutOrderRecDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => NavbarLayoutOrderRecRoute,
  } as any)
const NavbarLayoutOrderRecIdRoute = NavbarLayoutOrderRecIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NavbarLayoutOrderRecRoute,
} as any)
const NavbarLayoutKardpollListRoute =
  NavbarLayoutKardpollListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => NavbarLayoutKardpollRoute,
  } as any)
const NavbarLayoutFleetListRoute = NavbarLayoutFleetListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => NavbarLayoutFleetRoute,
} as any)
const NavbarLayoutDailyReportsShiftWorksheetRoute =
  NavbarLayoutDailyReportsShiftWorksheetRouteImport.update({
    id: '/shift-worksheet',
    path: '/shift-worksheet',
    getParentRoute: () => NavbarLayoutDailyReportsRoute,
  } as any)
const NavbarLayoutDailyReportsCashSummaryRoute =
  NavbarLayoutDailyReportsCashSummaryRouteImport.update({
    id: '/cash-summary',
    path: '/cash-summary',
    getParentRoute: () => NavbarLayoutDailyReportsRoute,
  } as any)
const NavbarLayoutCycleCountListRoute =
  NavbarLayoutCycleCountListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => NavbarLayoutCycleCountRoute,
  } as any)
const NavbarLayoutAuditTemplatesRoute =
  NavbarLayoutAuditTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => NavbarLayoutAuditRoute,
  } as any)
const NavbarLayoutAuditChecklistRoute =
  NavbarLayoutAuditChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => NavbarLayoutAuditRoute,
  } as any)
const NavbarLayoutSettingsUsersIndexRoute =
  NavbarLayoutSettingsUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutSettingsUsersRoute,
  } as any)
const NavbarLayoutSettingsPermissionsIndexRoute =
  NavbarLayoutSettingsPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => NavbarLayoutSettingsRoute,
  } as any)
const NavbarLayoutSettingsPaypointsIndexRoute =
  NavbarLayoutSettingsPaypointsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutSettingsPaypointsRoute,
  } as any)
const NavbarLayoutReportsSalesSummaryIndexRoute =
  NavbarLayoutReportsSalesSummaryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutReportsSalesSummaryRoute,
  } as any)
const NavbarLayoutDailyReportsShiftWorksheetIndexRoute =
  NavbarLayoutDailyReportsShiftWorksheetIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutDailyReportsShiftWorksheetRoute,
  } as any)
const NavbarLayoutAuditChecklistIndexRoute =
  NavbarLayoutAuditChecklistIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutAuditChecklistRoute,
  } as any)
const NavbarLayoutVendorEditIdRoute =
  NavbarLayoutVendorEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => NavbarLayoutVendorRoute,
  } as any)
const NavbarLayoutSettingsUsersUserIdRoute =
  NavbarLayoutSettingsUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => NavbarLayoutSettingsUsersRoute,
  } as any)
const NavbarLayoutSettingsPaypointsSiteRoute =
  NavbarLayoutSettingsPaypointsSiteRouteImport.update({
    id: '/$site',
    path: '/$site',
    getParentRoute: () => NavbarLayoutSettingsPaypointsRoute,
  } as any)
const NavbarLayoutReportsSalesSummaryUploadRoute =
  NavbarLayoutReportsSalesSummaryUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => NavbarLayoutReportsSalesSummaryRoute,
  } as any)
const NavbarLayoutDailyReportsShiftWorksheetCreateRoute =
  NavbarLayoutDailyReportsShiftWorksheetCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => NavbarLayoutDailyReportsShiftWorksheetRoute,
  } as any)
const NavbarLayoutDailyReportsShiftWorksheetWorksheetRoute =
  NavbarLayoutDailyReportsShiftWorksheetWorksheetRouteImport.update({
    id: '/$worksheet',
    path: '/$worksheet',
    getParentRoute: () => NavbarLayoutDailyReportsShiftWorksheetRoute,
  } as any)
const NavbarLayoutCycleCountEntryIdRoute =
  NavbarLayoutCycleCountEntryIdRouteImport.update({
    id: '/entry/$id',
    path: '/entry/$id',
    getParentRoute: () => NavbarLayoutCycleCountRoute,
  } as any)
const NavbarLayoutAuditTemplatesSelectRoute =
  NavbarLayoutAuditTemplatesSelectRouteImport.update({
    id: '/select',
    path: '/select',
    getParentRoute: () => NavbarLayoutAuditTemplatesRoute,
  } as any)
const NavbarLayoutAuditTemplatesChecklistRoute =
  NavbarLayoutAuditTemplatesChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => NavbarLayoutAuditTemplatesRoute,
  } as any)
const NavbarLayoutAuditChecklistIdRoute =
  NavbarLayoutAuditChecklistIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => NavbarLayoutAuditChecklistRoute,
  } as any)
const NavbarLayoutAuditTemplatesSelectIndexRoute =
  NavbarLayoutAuditTemplatesSelectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutAuditTemplatesSelectRoute,
  } as any)
const NavbarLayoutAuditTemplatesChecklistIndexRoute =
  NavbarLayoutAuditTemplatesChecklistIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutAuditTemplatesChecklistRoute,
  } as any)
const NavbarLayoutAuditTemplatesSelectListRoute =
  NavbarLayoutAuditTemplatesSelectListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => NavbarLayoutAuditTemplatesSelectRoute,
  } as any)
const NavbarLayoutAuditTemplatesSelectIdRoute =
  NavbarLayoutAuditTemplatesSelectIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => NavbarLayoutAuditTemplatesSelectRoute,
  } as any)
const NavbarLayoutAuditTemplatesChecklistListRoute =
  NavbarLayoutAuditTemplatesChecklistListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => NavbarLayoutAuditTemplatesChecklistRoute,
  } as any)
const NavbarLayoutAuditTemplatesChecklistIdRoute =
  NavbarLayoutAuditTemplatesChecklistIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => NavbarLayoutAuditTemplatesChecklistRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/audit': typeof NavbarLayoutAuditRouteWithChildren
  '/cycle-count': typeof NavbarLayoutCycleCountRouteWithChildren
  '/daily-reports': typeof NavbarLayoutDailyReportsRouteWithChildren
  '/fleet': typeof NavbarLayoutFleetRouteWithChildren
  '/kardpoll': typeof NavbarLayoutKardpollRouteWithChildren
  '/order-rec': typeof NavbarLayoutOrderRecRouteWithChildren
  '/payables': typeof NavbarLayoutPayablesRouteWithChildren
  '/po': typeof NavbarLayoutPoRouteWithChildren
  '/reports': typeof NavbarLayoutReportsRouteWithChildren
  '/settings': typeof NavbarLayoutSettingsRouteWithChildren
  '/status': typeof NavbarLayoutStatusRouteWithChildren
  '/vendor': typeof NavbarLayoutVendorRouteWithChildren
  '/': typeof NavbarLayoutIndexRoute
  '/audit/checklist': typeof NavbarLayoutAuditChecklistRouteWithChildren
  '/audit/templates': typeof NavbarLayoutAuditTemplatesRouteWithChildren
  '/cycle-count/list': typeof NavbarLayoutCycleCountListRoute
  '/daily-reports/cash-summary': typeof NavbarLayoutDailyReportsCashSummaryRoute
  '/daily-reports/shift-worksheet': typeof NavbarLayoutDailyReportsShiftWorksheetRouteWithChildren
  '/fleet/list': typeof NavbarLayoutFleetListRoute
  '/kardpoll/list': typeof NavbarLayoutKardpollListRoute
  '/order-rec/$id': typeof NavbarLayoutOrderRecIdRoute
  '/order-rec/dashboard': typeof NavbarLayoutOrderRecDashboardRoute
  '/order-rec/list': typeof NavbarLayoutOrderRecListRoute
  '/payables/images': typeof NavbarLayoutPayablesImagesRoute
  '/payables/list': typeof NavbarLayoutPayablesListRoute
  '/payables/review': typeof NavbarLayoutPayablesReviewRoute
  '/po/list': typeof NavbarLayoutPoListRoute
  '/po/receipt': typeof NavbarLayoutPoReceiptRoute
  '/po/signature': typeof NavbarLayoutPoSignatureRoute
  '/reports/other': typeof NavbarLayoutReportsOtherRoute
  '/reports/sales-summary': typeof NavbarLayoutReportsSalesSummaryRouteWithChildren
  '/settings/paypoints': typeof NavbarLayoutSettingsPaypointsRouteWithChildren
  '/settings/users': typeof NavbarLayoutSettingsUsersRouteWithChildren
  '/status/list': typeof NavbarLayoutStatusListRoute
  '/vendor/list': typeof NavbarLayoutVendorListRoute
  '/audit/': typeof NavbarLayoutAuditIndexRoute
  '/cycle-count/': typeof NavbarLayoutCycleCountIndexRoute
  '/fleet/': typeof NavbarLayoutFleetIndexRoute
  '/kardpoll/': typeof NavbarLayoutKardpollIndexRoute
  '/order-rec/': typeof NavbarLayoutOrderRecIndexRoute
  '/payables/': typeof NavbarLayoutPayablesIndexRoute
  '/po/': typeof NavbarLayoutPoIndexRoute
  '/settings/': typeof NavbarLayoutSettingsIndexRoute
  '/status/': typeof NavbarLayoutStatusIndexRoute
  '/vendor/': typeof NavbarLayoutVendorIndexRoute
  '/audit/checklist/$id': typeof NavbarLayoutAuditChecklistIdRoute
  '/audit/templates/checklist': typeof NavbarLayoutAuditTemplatesChecklistRouteWithChildren
  '/audit/templates/select': typeof NavbarLayoutAuditTemplatesSelectRouteWithChildren
  '/cycle-count/entry/$id': typeof NavbarLayoutCycleCountEntryIdRoute
  '/daily-reports/shift-worksheet/$worksheet': typeof NavbarLayoutDailyReportsShiftWorksheetWorksheetRoute
  '/daily-reports/shift-worksheet/create': typeof NavbarLayoutDailyReportsShiftWorksheetCreateRoute
  '/reports/sales-summary/upload': typeof NavbarLayoutReportsSalesSummaryUploadRoute
  '/settings/paypoints/$site': typeof NavbarLayoutSettingsPaypointsSiteRoute
  '/settings/users/$userId': typeof NavbarLayoutSettingsUsersUserIdRoute
  '/vendor/edit/$id': typeof NavbarLayoutVendorEditIdRoute
  '/audit/checklist/': typeof NavbarLayoutAuditChecklistIndexRoute
  '/daily-reports/shift-worksheet/': typeof NavbarLayoutDailyReportsShiftWorksheetIndexRoute
  '/reports/sales-summary/': typeof NavbarLayoutReportsSalesSummaryIndexRoute
  '/settings/paypoints/': typeof NavbarLayoutSettingsPaypointsIndexRoute
  '/settings/permissions': typeof NavbarLayoutSettingsPermissionsIndexRoute
  '/settings/users/': typeof NavbarLayoutSettingsUsersIndexRoute
  '/audit/templates/checklist/$id': typeof NavbarLayoutAuditTemplatesChecklistIdRoute
  '/audit/templates/checklist/list': typeof NavbarLayoutAuditTemplatesChecklistListRoute
  '/audit/templates/select/$id': typeof NavbarLayoutAuditTemplatesSelectIdRoute
  '/audit/templates/select/list': typeof NavbarLayoutAuditTemplatesSelectListRoute
  '/audit/templates/checklist/': typeof NavbarLayoutAuditTemplatesChecklistIndexRoute
  '/audit/templates/select/': typeof NavbarLayoutAuditTemplatesSelectIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/daily-reports': typeof NavbarLayoutDailyReportsRouteWithChildren
  '/reports': typeof NavbarLayoutReportsRouteWithChildren
  '/': typeof NavbarLayoutIndexRoute
  '/audit/templates': typeof NavbarLayoutAuditTemplatesRouteWithChildren
  '/cycle-count/list': typeof NavbarLayoutCycleCountListRoute
  '/daily-reports/cash-summary': typeof NavbarLayoutDailyReportsCashSummaryRoute
  '/fleet/list': typeof NavbarLayoutFleetListRoute
  '/kardpoll/list': typeof NavbarLayoutKardpollListRoute
  '/order-rec/$id': typeof NavbarLayoutOrderRecIdRoute
  '/order-rec/dashboard': typeof NavbarLayoutOrderRecDashboardRoute
  '/order-rec/list': typeof NavbarLayoutOrderRecListRoute
  '/payables/images': typeof NavbarLayoutPayablesImagesRoute
  '/payables/list': typeof NavbarLayoutPayablesListRoute
  '/payables/review': typeof NavbarLayoutPayablesReviewRoute
  '/po/list': typeof NavbarLayoutPoListRoute
  '/po/receipt': typeof NavbarLayoutPoReceiptRoute
  '/po/signature': typeof NavbarLayoutPoSignatureRoute
  '/reports/other': typeof NavbarLayoutReportsOtherRoute
  '/status/list': typeof NavbarLayoutStatusListRoute
  '/vendor/list': typeof NavbarLayoutVendorListRoute
  '/audit': typeof NavbarLayoutAuditIndexRoute
  '/cycle-count': typeof NavbarLayoutCycleCountIndexRoute
  '/fleet': typeof NavbarLayoutFleetIndexRoute
  '/kardpoll': typeof NavbarLayoutKardpollIndexRoute
  '/order-rec': typeof NavbarLayoutOrderRecIndexRoute
  '/payables': typeof NavbarLayoutPayablesIndexRoute
  '/po': typeof NavbarLayoutPoIndexRoute
  '/settings': typeof NavbarLayoutSettingsIndexRoute
  '/status': typeof NavbarLayoutStatusIndexRoute
  '/vendor': typeof NavbarLayoutVendorIndexRoute
  '/audit/checklist/$id': typeof NavbarLayoutAuditChecklistIdRoute
  '/cycle-count/entry/$id': typeof NavbarLayoutCycleCountEntryIdRoute
  '/daily-reports/shift-worksheet/$worksheet': typeof NavbarLayoutDailyReportsShiftWorksheetWorksheetRoute
  '/daily-reports/shift-worksheet/create': typeof NavbarLayoutDailyReportsShiftWorksheetCreateRoute
  '/reports/sales-summary/upload': typeof NavbarLayoutReportsSalesSummaryUploadRoute
  '/settings/paypoints/$site': typeof NavbarLayoutSettingsPaypointsSiteRoute
  '/settings/users/$userId': typeof NavbarLayoutSettingsUsersUserIdRoute
  '/vendor/edit/$id': typeof NavbarLayoutVendorEditIdRoute
  '/audit/checklist': typeof NavbarLayoutAuditChecklistIndexRoute
  '/daily-reports/shift-worksheet': typeof NavbarLayoutDailyReportsShiftWorksheetIndexRoute
  '/reports/sales-summary': typeof NavbarLayoutReportsSalesSummaryIndexRoute
  '/settings/paypoints': typeof NavbarLayoutSettingsPaypointsIndexRoute
  '/settings/permissions': typeof NavbarLayoutSettingsPermissionsIndexRoute
  '/settings/users': typeof NavbarLayoutSettingsUsersIndexRoute
  '/audit/templates/checklist/$id': typeof NavbarLayoutAuditTemplatesChecklistIdRoute
  '/audit/templates/checklist/list': typeof NavbarLayoutAuditTemplatesChecklistListRoute
  '/audit/templates/select/$id': typeof NavbarLayoutAuditTemplatesSelectIdRoute
  '/audit/templates/select/list': typeof NavbarLayoutAuditTemplatesSelectListRoute
  '/audit/templates/checklist': typeof NavbarLayoutAuditTemplatesChecklistIndexRoute
  '/audit/templates/select': typeof NavbarLayoutAuditTemplatesSelectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_navbarLayout': typeof NavbarLayoutRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_navbarLayout/audit': typeof NavbarLayoutAuditRouteWithChildren
  '/_navbarLayout/cycle-count': typeof NavbarLayoutCycleCountRouteWithChildren
  '/_navbarLayout/daily-reports': typeof NavbarLayoutDailyReportsRouteWithChildren
  '/_navbarLayout/fleet': typeof NavbarLayoutFleetRouteWithChildren
  '/_navbarLayout/kardpoll': typeof NavbarLayoutKardpollRouteWithChildren
  '/_navbarLayout/order-rec': typeof NavbarLayoutOrderRecRouteWithChildren
  '/_navbarLayout/payables': typeof NavbarLayoutPayablesRouteWithChildren
  '/_navbarLayout/po': typeof NavbarLayoutPoRouteWithChildren
  '/_navbarLayout/reports': typeof NavbarLayoutReportsRouteWithChildren
  '/_navbarLayout/settings': typeof NavbarLayoutSettingsRouteWithChildren
  '/_navbarLayout/status': typeof NavbarLayoutStatusRouteWithChildren
  '/_navbarLayout/vendor': typeof NavbarLayoutVendorRouteWithChildren
  '/_navbarLayout/': typeof NavbarLayoutIndexRoute
  '/_navbarLayout/audit/checklist': typeof NavbarLayoutAuditChecklistRouteWithChildren
  '/_navbarLayout/audit/templates': typeof NavbarLayoutAuditTemplatesRouteWithChildren
  '/_navbarLayout/cycle-count/list': typeof NavbarLayoutCycleCountListRoute
  '/_navbarLayout/daily-reports/cash-summary': typeof NavbarLayoutDailyReportsCashSummaryRoute
  '/_navbarLayout/daily-reports/shift-worksheet': typeof NavbarLayoutDailyReportsShiftWorksheetRouteWithChildren
  '/_navbarLayout/fleet/list': typeof NavbarLayoutFleetListRoute
  '/_navbarLayout/kardpoll/list': typeof NavbarLayoutKardpollListRoute
  '/_navbarLayout/order-rec/$id': typeof NavbarLayoutOrderRecIdRoute
  '/_navbarLayout/order-rec/dashboard': typeof NavbarLayoutOrderRecDashboardRoute
  '/_navbarLayout/order-rec/list': typeof NavbarLayoutOrderRecListRoute
  '/_navbarLayout/payables/images': typeof NavbarLayoutPayablesImagesRoute
  '/_navbarLayout/payables/list': typeof NavbarLayoutPayablesListRoute
  '/_navbarLayout/payables/review': typeof NavbarLayoutPayablesReviewRoute
  '/_navbarLayout/po/list': typeof NavbarLayoutPoListRoute
  '/_navbarLayout/po/receipt': typeof NavbarLayoutPoReceiptRoute
  '/_navbarLayout/po/signature': typeof NavbarLayoutPoSignatureRoute
  '/_navbarLayout/reports/other': typeof NavbarLayoutReportsOtherRoute
  '/_navbarLayout/reports/sales-summary': typeof NavbarLayoutReportsSalesSummaryRouteWithChildren
  '/_navbarLayout/settings/paypoints': typeof NavbarLayoutSettingsPaypointsRouteWithChildren
  '/_navbarLayout/settings/users': typeof NavbarLayoutSettingsUsersRouteWithChildren
  '/_navbarLayout/status/list': typeof NavbarLayoutStatusListRoute
  '/_navbarLayout/vendor/list': typeof NavbarLayoutVendorListRoute
  '/_navbarLayout/audit/': typeof NavbarLayoutAuditIndexRoute
  '/_navbarLayout/cycle-count/': typeof NavbarLayoutCycleCountIndexRoute
  '/_navbarLayout/fleet/': typeof NavbarLayoutFleetIndexRoute
  '/_navbarLayout/kardpoll/': typeof NavbarLayoutKardpollIndexRoute
  '/_navbarLayout/order-rec/': typeof NavbarLayoutOrderRecIndexRoute
  '/_navbarLayout/payables/': typeof NavbarLayoutPayablesIndexRoute
  '/_navbarLayout/po/': typeof NavbarLayoutPoIndexRoute
  '/_navbarLayout/settings/': typeof NavbarLayoutSettingsIndexRoute
  '/_navbarLayout/status/': typeof NavbarLayoutStatusIndexRoute
  '/_navbarLayout/vendor/': typeof NavbarLayoutVendorIndexRoute
  '/_navbarLayout/audit/checklist/$id': typeof NavbarLayoutAuditChecklistIdRoute
  '/_navbarLayout/audit/templates/checklist': typeof NavbarLayoutAuditTemplatesChecklistRouteWithChildren
  '/_navbarLayout/audit/templates/select': typeof NavbarLayoutAuditTemplatesSelectRouteWithChildren
  '/_navbarLayout/cycle-count/entry/$id': typeof NavbarLayoutCycleCountEntryIdRoute
  '/_navbarLayout/daily-reports/shift-worksheet/$worksheet': typeof NavbarLayoutDailyReportsShiftWorksheetWorksheetRoute
  '/_navbarLayout/daily-reports/shift-worksheet/create': typeof NavbarLayoutDailyReportsShiftWorksheetCreateRoute
  '/_navbarLayout/reports/sales-summary/upload': typeof NavbarLayoutReportsSalesSummaryUploadRoute
  '/_navbarLayout/settings/paypoints/$site': typeof NavbarLayoutSettingsPaypointsSiteRoute
  '/_navbarLayout/settings/users/$userId': typeof NavbarLayoutSettingsUsersUserIdRoute
  '/_navbarLayout/vendor/edit/$id': typeof NavbarLayoutVendorEditIdRoute
  '/_navbarLayout/audit/checklist/': typeof NavbarLayoutAuditChecklistIndexRoute
  '/_navbarLayout/daily-reports/shift-worksheet/': typeof NavbarLayoutDailyReportsShiftWorksheetIndexRoute
  '/_navbarLayout/reports/sales-summary/': typeof NavbarLayoutReportsSalesSummaryIndexRoute
  '/_navbarLayout/settings/paypoints/': typeof NavbarLayoutSettingsPaypointsIndexRoute
  '/_navbarLayout/settings/permissions/': typeof NavbarLayoutSettingsPermissionsIndexRoute
  '/_navbarLayout/settings/users/': typeof NavbarLayoutSettingsUsersIndexRoute
  '/_navbarLayout/audit/templates/checklist/$id': typeof NavbarLayoutAuditTemplatesChecklistIdRoute
  '/_navbarLayout/audit/templates/checklist/list': typeof NavbarLayoutAuditTemplatesChecklistListRoute
  '/_navbarLayout/audit/templates/select/$id': typeof NavbarLayoutAuditTemplatesSelectIdRoute
  '/_navbarLayout/audit/templates/select/list': typeof NavbarLayoutAuditTemplatesSelectListRoute
  '/_navbarLayout/audit/templates/checklist/': typeof NavbarLayoutAuditTemplatesChecklistIndexRoute
  '/_navbarLayout/audit/templates/select/': typeof NavbarLayoutAuditTemplatesSelectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/audit'
    | '/cycle-count'
    | '/daily-reports'
    | '/fleet'
    | '/kardpoll'
    | '/order-rec'
    | '/payables'
    | '/po'
    | '/reports'
    | '/settings'
    | '/status'
    | '/vendor'
    | '/'
    | '/audit/checklist'
    | '/audit/templates'
    | '/cycle-count/list'
    | '/daily-reports/cash-summary'
    | '/daily-reports/shift-worksheet'
    | '/fleet/list'
    | '/kardpoll/list'
    | '/order-rec/$id'
    | '/order-rec/dashboard'
    | '/order-rec/list'
    | '/payables/images'
    | '/payables/list'
    | '/payables/review'
    | '/po/list'
    | '/po/receipt'
    | '/po/signature'
    | '/reports/other'
    | '/reports/sales-summary'
    | '/settings/paypoints'
    | '/settings/users'
    | '/status/list'
    | '/vendor/list'
    | '/audit/'
    | '/cycle-count/'
    | '/fleet/'
    | '/kardpoll/'
    | '/order-rec/'
    | '/payables/'
    | '/po/'
    | '/settings/'
    | '/status/'
    | '/vendor/'
    | '/audit/checklist/$id'
    | '/audit/templates/checklist'
    | '/audit/templates/select'
    | '/cycle-count/entry/$id'
    | '/daily-reports/shift-worksheet/$worksheet'
    | '/daily-reports/shift-worksheet/create'
    | '/reports/sales-summary/upload'
    | '/settings/paypoints/$site'
    | '/settings/users/$userId'
    | '/vendor/edit/$id'
    | '/audit/checklist/'
    | '/daily-reports/shift-worksheet/'
    | '/reports/sales-summary/'
    | '/settings/paypoints/'
    | '/settings/permissions'
    | '/settings/users/'
    | '/audit/templates/checklist/$id'
    | '/audit/templates/checklist/list'
    | '/audit/templates/select/$id'
    | '/audit/templates/select/list'
    | '/audit/templates/checklist/'
    | '/audit/templates/select/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/daily-reports'
    | '/reports'
    | '/'
    | '/audit/templates'
    | '/cycle-count/list'
    | '/daily-reports/cash-summary'
    | '/fleet/list'
    | '/kardpoll/list'
    | '/order-rec/$id'
    | '/order-rec/dashboard'
    | '/order-rec/list'
    | '/payables/images'
    | '/payables/list'
    | '/payables/review'
    | '/po/list'
    | '/po/receipt'
    | '/po/signature'
    | '/reports/other'
    | '/status/list'
    | '/vendor/list'
    | '/audit'
    | '/cycle-count'
    | '/fleet'
    | '/kardpoll'
    | '/order-rec'
    | '/payables'
    | '/po'
    | '/settings'
    | '/status'
    | '/vendor'
    | '/audit/checklist/$id'
    | '/cycle-count/entry/$id'
    | '/daily-reports/shift-worksheet/$worksheet'
    | '/daily-reports/shift-worksheet/create'
    | '/reports/sales-summary/upload'
    | '/settings/paypoints/$site'
    | '/settings/users/$userId'
    | '/vendor/edit/$id'
    | '/audit/checklist'
    | '/daily-reports/shift-worksheet'
    | '/reports/sales-summary'
    | '/settings/paypoints'
    | '/settings/permissions'
    | '/settings/users'
    | '/audit/templates/checklist/$id'
    | '/audit/templates/checklist/list'
    | '/audit/templates/select/$id'
    | '/audit/templates/select/list'
    | '/audit/templates/checklist'
    | '/audit/templates/select'
  id:
    | '__root__'
    | '/_navbarLayout'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_navbarLayout/audit'
    | '/_navbarLayout/cycle-count'
    | '/_navbarLayout/daily-reports'
    | '/_navbarLayout/fleet'
    | '/_navbarLayout/kardpoll'
    | '/_navbarLayout/order-rec'
    | '/_navbarLayout/payables'
    | '/_navbarLayout/po'
    | '/_navbarLayout/reports'
    | '/_navbarLayout/settings'
    | '/_navbarLayout/status'
    | '/_navbarLayout/vendor'
    | '/_navbarLayout/'
    | '/_navbarLayout/audit/checklist'
    | '/_navbarLayout/audit/templates'
    | '/_navbarLayout/cycle-count/list'
    | '/_navbarLayout/daily-reports/cash-summary'
    | '/_navbarLayout/daily-reports/shift-worksheet'
    | '/_navbarLayout/fleet/list'
    | '/_navbarLayout/kardpoll/list'
    | '/_navbarLayout/order-rec/$id'
    | '/_navbarLayout/order-rec/dashboard'
    | '/_navbarLayout/order-rec/list'
    | '/_navbarLayout/payables/images'
    | '/_navbarLayout/payables/list'
    | '/_navbarLayout/payables/review'
    | '/_navbarLayout/po/list'
    | '/_navbarLayout/po/receipt'
    | '/_navbarLayout/po/signature'
    | '/_navbarLayout/reports/other'
    | '/_navbarLayout/reports/sales-summary'
    | '/_navbarLayout/settings/paypoints'
    | '/_navbarLayout/settings/users'
    | '/_navbarLayout/status/list'
    | '/_navbarLayout/vendor/list'
    | '/_navbarLayout/audit/'
    | '/_navbarLayout/cycle-count/'
    | '/_navbarLayout/fleet/'
    | '/_navbarLayout/kardpoll/'
    | '/_navbarLayout/order-rec/'
    | '/_navbarLayout/payables/'
    | '/_navbarLayout/po/'
    | '/_navbarLayout/settings/'
    | '/_navbarLayout/status/'
    | '/_navbarLayout/vendor/'
    | '/_navbarLayout/audit/checklist/$id'
    | '/_navbarLayout/audit/templates/checklist'
    | '/_navbarLayout/audit/templates/select'
    | '/_navbarLayout/cycle-count/entry/$id'
    | '/_navbarLayout/daily-reports/shift-worksheet/$worksheet'
    | '/_navbarLayout/daily-reports/shift-worksheet/create'
    | '/_navbarLayout/reports/sales-summary/upload'
    | '/_navbarLayout/settings/paypoints/$site'
    | '/_navbarLayout/settings/users/$userId'
    | '/_navbarLayout/vendor/edit/$id'
    | '/_navbarLayout/audit/checklist/'
    | '/_navbarLayout/daily-reports/shift-worksheet/'
    | '/_navbarLayout/reports/sales-summary/'
    | '/_navbarLayout/settings/paypoints/'
    | '/_navbarLayout/settings/permissions/'
    | '/_navbarLayout/settings/users/'
    | '/_navbarLayout/audit/templates/checklist/$id'
    | '/_navbarLayout/audit/templates/checklist/list'
    | '/_navbarLayout/audit/templates/select/$id'
    | '/_navbarLayout/audit/templates/select/list'
    | '/_navbarLayout/audit/templates/checklist/'
    | '/_navbarLayout/audit/templates/select/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NavbarLayoutRoute: typeof NavbarLayoutRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_navbarLayout': {
      id: '/_navbarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavbarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbarLayout/': {
      id: '/_navbarLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NavbarLayoutIndexRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/vendor': {
      id: '/_navbarLayout/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof NavbarLayoutVendorRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/status': {
      id: '/_navbarLayout/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof NavbarLayoutStatusRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/settings': {
      id: '/_navbarLayout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof NavbarLayoutSettingsRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/reports': {
      id: '/_navbarLayout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof NavbarLayoutReportsRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/po': {
      id: '/_navbarLayout/po'
      path: '/po'
      fullPath: '/po'
      preLoaderRoute: typeof NavbarLayoutPoRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/payables': {
      id: '/_navbarLayout/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof NavbarLayoutPayablesRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/order-rec': {
      id: '/_navbarLayout/order-rec'
      path: '/order-rec'
      fullPath: '/order-rec'
      preLoaderRoute: typeof NavbarLayoutOrderRecRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/kardpoll': {
      id: '/_navbarLayout/kardpoll'
      path: '/kardpoll'
      fullPath: '/kardpoll'
      preLoaderRoute: typeof NavbarLayoutKardpollRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/fleet': {
      id: '/_navbarLayout/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof NavbarLayoutFleetRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/daily-reports': {
      id: '/_navbarLayout/daily-reports'
      path: '/daily-reports'
      fullPath: '/daily-reports'
      preLoaderRoute: typeof NavbarLayoutDailyReportsRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/cycle-count': {
      id: '/_navbarLayout/cycle-count'
      path: '/cycle-count'
      fullPath: '/cycle-count'
      preLoaderRoute: typeof NavbarLayoutCycleCountRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbarLayout/audit': {
      id: '/_navbarLayout/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof NavbarLayoutAuditRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbarLayout/vendor/': {
      id: '/_navbarLayout/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof NavbarLayoutVendorIndexRouteImport
      parentRoute: typeof NavbarLayoutVendorRoute
    }
    '/_navbarLayout/status/': {
      id: '/_navbarLayout/status/'
      path: '/'
      fullPath: '/status/'
      preLoaderRoute: typeof NavbarLayoutStatusIndexRouteImport
      parentRoute: typeof NavbarLayoutStatusRoute
    }
    '/_navbarLayout/settings/': {
      id: '/_navbarLayout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof NavbarLayoutSettingsIndexRouteImport
      parentRoute: typeof NavbarLayoutSettingsRoute
    }
    '/_navbarLayout/po/': {
      id: '/_navbarLayout/po/'
      path: '/'
      fullPath: '/po/'
      preLoaderRoute: typeof NavbarLayoutPoIndexRouteImport
      parentRoute: typeof NavbarLayoutPoRoute
    }
    '/_navbarLayout/payables/': {
      id: '/_navbarLayout/payables/'
      path: '/'
      fullPath: '/payables/'
      preLoaderRoute: typeof NavbarLayoutPayablesIndexRouteImport
      parentRoute: typeof NavbarLayoutPayablesRoute
    }
    '/_navbarLayout/order-rec/': {
      id: '/_navbarLayout/order-rec/'
      path: '/'
      fullPath: '/order-rec/'
      preLoaderRoute: typeof NavbarLayoutOrderRecIndexRouteImport
      parentRoute: typeof NavbarLayoutOrderRecRoute
    }
    '/_navbarLayout/kardpoll/': {
      id: '/_navbarLayout/kardpoll/'
      path: '/'
      fullPath: '/kardpoll/'
      preLoaderRoute: typeof NavbarLayoutKardpollIndexRouteImport
      parentRoute: typeof NavbarLayoutKardpollRoute
    }
    '/_navbarLayout/fleet/': {
      id: '/_navbarLayout/fleet/'
      path: '/'
      fullPath: '/fleet/'
      preLoaderRoute: typeof NavbarLayoutFleetIndexRouteImport
      parentRoute: typeof NavbarLayoutFleetRoute
    }
    '/_navbarLayout/cycle-count/': {
      id: '/_navbarLayout/cycle-count/'
      path: '/'
      fullPath: '/cycle-count/'
      preLoaderRoute: typeof NavbarLayoutCycleCountIndexRouteImport
      parentRoute: typeof NavbarLayoutCycleCountRoute
    }
    '/_navbarLayout/audit/': {
      id: '/_navbarLayout/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof NavbarLayoutAuditIndexRouteImport
      parentRoute: typeof NavbarLayoutAuditRoute
    }
    '/_navbarLayout/vendor/list': {
      id: '/_navbarLayout/vendor/list'
      path: '/list'
      fullPath: '/vendor/list'
      preLoaderRoute: typeof NavbarLayoutVendorListRouteImport
      parentRoute: typeof NavbarLayoutVendorRoute
    }
    '/_navbarLayout/status/list': {
      id: '/_navbarLayout/status/list'
      path: '/list'
      fullPath: '/status/list'
      preLoaderRoute: typeof NavbarLayoutStatusListRouteImport
      parentRoute: typeof NavbarLayoutStatusRoute
    }
    '/_navbarLayout/settings/users': {
      id: '/_navbarLayout/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof NavbarLayoutSettingsUsersRouteImport
      parentRoute: typeof NavbarLayoutSettingsRoute
    }
    '/_navbarLayout/settings/paypoints': {
      id: '/_navbarLayout/settings/paypoints'
      path: '/paypoints'
      fullPath: '/settings/paypoints'
      preLoaderRoute: typeof NavbarLayoutSettingsPaypointsRouteImport
      parentRoute: typeof NavbarLayoutSettingsRoute
    }
    '/_navbarLayout/reports/sales-summary': {
      id: '/_navbarLayout/reports/sales-summary'
      path: '/sales-summary'
      fullPath: '/reports/sales-summary'
      preLoaderRoute: typeof NavbarLayoutReportsSalesSummaryRouteImport
      parentRoute: typeof NavbarLayoutReportsRoute
    }
    '/_navbarLayout/reports/other': {
      id: '/_navbarLayout/reports/other'
      path: '/other'
      fullPath: '/reports/other'
      preLoaderRoute: typeof NavbarLayoutReportsOtherRouteImport
      parentRoute: typeof NavbarLayoutReportsRoute
    }
    '/_navbarLayout/po/signature': {
      id: '/_navbarLayout/po/signature'
      path: '/signature'
      fullPath: '/po/signature'
      preLoaderRoute: typeof NavbarLayoutPoSignatureRouteImport
      parentRoute: typeof NavbarLayoutPoRoute
    }
    '/_navbarLayout/po/receipt': {
      id: '/_navbarLayout/po/receipt'
      path: '/receipt'
      fullPath: '/po/receipt'
      preLoaderRoute: typeof NavbarLayoutPoReceiptRouteImport
      parentRoute: typeof NavbarLayoutPoRoute
    }
    '/_navbarLayout/po/list': {
      id: '/_navbarLayout/po/list'
      path: '/list'
      fullPath: '/po/list'
      preLoaderRoute: typeof NavbarLayoutPoListRouteImport
      parentRoute: typeof NavbarLayoutPoRoute
    }
    '/_navbarLayout/payables/review': {
      id: '/_navbarLayout/payables/review'
      path: '/review'
      fullPath: '/payables/review'
      preLoaderRoute: typeof NavbarLayoutPayablesReviewRouteImport
      parentRoute: typeof NavbarLayoutPayablesRoute
    }
    '/_navbarLayout/payables/list': {
      id: '/_navbarLayout/payables/list'
      path: '/list'
      fullPath: '/payables/list'
      preLoaderRoute: typeof NavbarLayoutPayablesListRouteImport
      parentRoute: typeof NavbarLayoutPayablesRoute
    }
    '/_navbarLayout/payables/images': {
      id: '/_navbarLayout/payables/images'
      path: '/images'
      fullPath: '/payables/images'
      preLoaderRoute: typeof NavbarLayoutPayablesImagesRouteImport
      parentRoute: typeof NavbarLayoutPayablesRoute
    }
    '/_navbarLayout/order-rec/list': {
      id: '/_navbarLayout/order-rec/list'
      path: '/list'
      fullPath: '/order-rec/list'
      preLoaderRoute: typeof NavbarLayoutOrderRecListRouteImport
      parentRoute: typeof NavbarLayoutOrderRecRoute
    }
    '/_navbarLayout/order-rec/dashboard': {
      id: '/_navbarLayout/order-rec/dashboard'
      path: '/dashboard'
      fullPath: '/order-rec/dashboard'
      preLoaderRoute: typeof NavbarLayoutOrderRecDashboardRouteImport
      parentRoute: typeof NavbarLayoutOrderRecRoute
    }
    '/_navbarLayout/order-rec/$id': {
      id: '/_navbarLayout/order-rec/$id'
      path: '/$id'
      fullPath: '/order-rec/$id'
      preLoaderRoute: typeof NavbarLayoutOrderRecIdRouteImport
      parentRoute: typeof NavbarLayoutOrderRecRoute
    }
    '/_navbarLayout/kardpoll/list': {
      id: '/_navbarLayout/kardpoll/list'
      path: '/list'
      fullPath: '/kardpoll/list'
      preLoaderRoute: typeof NavbarLayoutKardpollListRouteImport
      parentRoute: typeof NavbarLayoutKardpollRoute
    }
    '/_navbarLayout/fleet/list': {
      id: '/_navbarLayout/fleet/list'
      path: '/list'
      fullPath: '/fleet/list'
      preLoaderRoute: typeof NavbarLayoutFleetListRouteImport
      parentRoute: typeof NavbarLayoutFleetRoute
    }
    '/_navbarLayout/daily-reports/shift-worksheet': {
      id: '/_navbarLayout/daily-reports/shift-worksheet'
      path: '/shift-worksheet'
      fullPath: '/daily-reports/shift-worksheet'
      preLoaderRoute: typeof NavbarLayoutDailyReportsShiftWorksheetRouteImport
      parentRoute: typeof NavbarLayoutDailyReportsRoute
    }
    '/_navbarLayout/daily-reports/cash-summary': {
      id: '/_navbarLayout/daily-reports/cash-summary'
      path: '/cash-summary'
      fullPath: '/daily-reports/cash-summary'
      preLoaderRoute: typeof NavbarLayoutDailyReportsCashSummaryRouteImport
      parentRoute: typeof NavbarLayoutDailyReportsRoute
    }
    '/_navbarLayout/cycle-count/list': {
      id: '/_navbarLayout/cycle-count/list'
      path: '/list'
      fullPath: '/cycle-count/list'
      preLoaderRoute: typeof NavbarLayoutCycleCountListRouteImport
      parentRoute: typeof NavbarLayoutCycleCountRoute
    }
    '/_navbarLayout/audit/templates': {
      id: '/_navbarLayout/audit/templates'
      path: '/templates'
      fullPath: '/audit/templates'
      preLoaderRoute: typeof NavbarLayoutAuditTemplatesRouteImport
      parentRoute: typeof NavbarLayoutAuditRoute
    }
    '/_navbarLayout/audit/checklist': {
      id: '/_navbarLayout/audit/checklist'
      path: '/checklist'
      fullPath: '/audit/checklist'
      preLoaderRoute: typeof NavbarLayoutAuditChecklistRouteImport
      parentRoute: typeof NavbarLayoutAuditRoute
    }
    '/_navbarLayout/settings/users/': {
      id: '/_navbarLayout/settings/users/'
      path: '/'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof NavbarLayoutSettingsUsersIndexRouteImport
      parentRoute: typeof NavbarLayoutSettingsUsersRoute
    }
    '/_navbarLayout/settings/permissions/': {
      id: '/_navbarLayout/settings/permissions/'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof NavbarLayoutSettingsPermissionsIndexRouteImport
      parentRoute: typeof NavbarLayoutSettingsRoute
    }
    '/_navbarLayout/settings/paypoints/': {
      id: '/_navbarLayout/settings/paypoints/'
      path: '/'
      fullPath: '/settings/paypoints/'
      preLoaderRoute: typeof NavbarLayoutSettingsPaypointsIndexRouteImport
      parentRoute: typeof NavbarLayoutSettingsPaypointsRoute
    }
    '/_navbarLayout/reports/sales-summary/': {
      id: '/_navbarLayout/reports/sales-summary/'
      path: '/'
      fullPath: '/reports/sales-summary/'
      preLoaderRoute: typeof NavbarLayoutReportsSalesSummaryIndexRouteImport
      parentRoute: typeof NavbarLayoutReportsSalesSummaryRoute
    }
    '/_navbarLayout/daily-reports/shift-worksheet/': {
      id: '/_navbarLayout/daily-reports/shift-worksheet/'
      path: '/'
      fullPath: '/daily-reports/shift-worksheet/'
      preLoaderRoute: typeof NavbarLayoutDailyReportsShiftWorksheetIndexRouteImport
      parentRoute: typeof NavbarLayoutDailyReportsShiftWorksheetRoute
    }
    '/_navbarLayout/audit/checklist/': {
      id: '/_navbarLayout/audit/checklist/'
      path: '/'
      fullPath: '/audit/checklist/'
      preLoaderRoute: typeof NavbarLayoutAuditChecklistIndexRouteImport
      parentRoute: typeof NavbarLayoutAuditChecklistRoute
    }
    '/_navbarLayout/vendor/edit/$id': {
      id: '/_navbarLayout/vendor/edit/$id'
      path: '/edit/$id'
      fullPath: '/vendor/edit/$id'
      preLoaderRoute: typeof NavbarLayoutVendorEditIdRouteImport
      parentRoute: typeof NavbarLayoutVendorRoute
    }
    '/_navbarLayout/settings/users/$userId': {
      id: '/_navbarLayout/settings/users/$userId'
      path: '/$userId'
      fullPath: '/settings/users/$userId'
      preLoaderRoute: typeof NavbarLayoutSettingsUsersUserIdRouteImport
      parentRoute: typeof NavbarLayoutSettingsUsersRoute
    }
    '/_navbarLayout/settings/paypoints/$site': {
      id: '/_navbarLayout/settings/paypoints/$site'
      path: '/$site'
      fullPath: '/settings/paypoints/$site'
      preLoaderRoute: typeof NavbarLayoutSettingsPaypointsSiteRouteImport
      parentRoute: typeof NavbarLayoutSettingsPaypointsRoute
    }
    '/_navbarLayout/reports/sales-summary/upload': {
      id: '/_navbarLayout/reports/sales-summary/upload'
      path: '/upload'
      fullPath: '/reports/sales-summary/upload'
      preLoaderRoute: typeof NavbarLayoutReportsSalesSummaryUploadRouteImport
      parentRoute: typeof NavbarLayoutReportsSalesSummaryRoute
    }
    '/_navbarLayout/daily-reports/shift-worksheet/create': {
      id: '/_navbarLayout/daily-reports/shift-worksheet/create'
      path: '/create'
      fullPath: '/daily-reports/shift-worksheet/create'
      preLoaderRoute: typeof NavbarLayoutDailyReportsShiftWorksheetCreateRouteImport
      parentRoute: typeof NavbarLayoutDailyReportsShiftWorksheetRoute
    }
    '/_navbarLayout/daily-reports/shift-worksheet/$worksheet': {
      id: '/_navbarLayout/daily-reports/shift-worksheet/$worksheet'
      path: '/$worksheet'
      fullPath: '/daily-reports/shift-worksheet/$worksheet'
      preLoaderRoute: typeof NavbarLayoutDailyReportsShiftWorksheetWorksheetRouteImport
      parentRoute: typeof NavbarLayoutDailyReportsShiftWorksheetRoute
    }
    '/_navbarLayout/cycle-count/entry/$id': {
      id: '/_navbarLayout/cycle-count/entry/$id'
      path: '/entry/$id'
      fullPath: '/cycle-count/entry/$id'
      preLoaderRoute: typeof NavbarLayoutCycleCountEntryIdRouteImport
      parentRoute: typeof NavbarLayoutCycleCountRoute
    }
    '/_navbarLayout/audit/templates/select': {
      id: '/_navbarLayout/audit/templates/select'
      path: '/select'
      fullPath: '/audit/templates/select'
      preLoaderRoute: typeof NavbarLayoutAuditTemplatesSelectRouteImport
      parentRoute: typeof NavbarLayoutAuditTemplatesRoute
    }
    '/_navbarLayout/audit/templates/checklist': {
      id: '/_navbarLayout/audit/templates/checklist'
      path: '/checklist'
      fullPath: '/audit/templates/checklist'
      preLoaderRoute: typeof NavbarLayoutAuditTemplatesChecklistRouteImport
      parentRoute: typeof NavbarLayoutAuditTemplatesRoute
    }
    '/_navbarLayout/audit/checklist/$id': {
      id: '/_navbarLayout/audit/checklist/$id'
      path: '/$id'
      fullPath: '/audit/checklist/$id'
      preLoaderRoute: typeof NavbarLayoutAuditChecklistIdRouteImport
      parentRoute: typeof NavbarLayoutAuditChecklistRoute
    }
    '/_navbarLayout/audit/templates/select/': {
      id: '/_navbarLayout/audit/templates/select/'
      path: '/'
      fullPath: '/audit/templates/select/'
      preLoaderRoute: typeof NavbarLayoutAuditTemplatesSelectIndexRouteImport
      parentRoute: typeof NavbarLayoutAuditTemplatesSelectRoute
    }
    '/_navbarLayout/audit/templates/checklist/': {
      id: '/_navbarLayout/audit/templates/checklist/'
      path: '/'
      fullPath: '/audit/templates/checklist/'
      preLoaderRoute: typeof NavbarLayoutAuditTemplatesChecklistIndexRouteImport
      parentRoute: typeof NavbarLayoutAuditTemplatesChecklistRoute
    }
    '/_navbarLayout/audit/templates/select/list': {
      id: '/_navbarLayout/audit/templates/select/list'
      path: '/list'
      fullPath: '/audit/templates/select/list'
      preLoaderRoute: typeof NavbarLayoutAuditTemplatesSelectListRouteImport
      parentRoute: typeof NavbarLayoutAuditTemplatesSelectRoute
    }
    '/_navbarLayout/audit/templates/select/$id': {
      id: '/_navbarLayout/audit/templates/select/$id'
      path: '/$id'
      fullPath: '/audit/templates/select/$id'
      preLoaderRoute: typeof NavbarLayoutAuditTemplatesSelectIdRouteImport
      parentRoute: typeof NavbarLayoutAuditTemplatesSelectRoute
    }
    '/_navbarLayout/audit/templates/checklist/list': {
      id: '/_navbarLayout/audit/templates/checklist/list'
      path: '/list'
      fullPath: '/audit/templates/checklist/list'
      preLoaderRoute: typeof NavbarLayoutAuditTemplatesChecklistListRouteImport
      parentRoute: typeof NavbarLayoutAuditTemplatesChecklistRoute
    }
    '/_navbarLayout/audit/templates/checklist/$id': {
      id: '/_navbarLayout/audit/templates/checklist/$id'
      path: '/$id'
      fullPath: '/audit/templates/checklist/$id'
      preLoaderRoute: typeof NavbarLayoutAuditTemplatesChecklistIdRouteImport
      parentRoute: typeof NavbarLayoutAuditTemplatesChecklistRoute
    }
  }
}

interface NavbarLayoutAuditChecklistRouteChildren {
  NavbarLayoutAuditChecklistIdRoute: typeof NavbarLayoutAuditChecklistIdRoute
  NavbarLayoutAuditChecklistIndexRoute: typeof NavbarLayoutAuditChecklistIndexRoute
}

const NavbarLayoutAuditChecklistRouteChildren: NavbarLayoutAuditChecklistRouteChildren =
  {
    NavbarLayoutAuditChecklistIdRoute: NavbarLayoutAuditChecklistIdRoute,
    NavbarLayoutAuditChecklistIndexRoute: NavbarLayoutAuditChecklistIndexRoute,
  }

const NavbarLayoutAuditChecklistRouteWithChildren =
  NavbarLayoutAuditChecklistRoute._addFileChildren(
    NavbarLayoutAuditChecklistRouteChildren,
  )

interface NavbarLayoutAuditTemplatesChecklistRouteChildren {
  NavbarLayoutAuditTemplatesChecklistIdRoute: typeof NavbarLayoutAuditTemplatesChecklistIdRoute
  NavbarLayoutAuditTemplatesChecklistListRoute: typeof NavbarLayoutAuditTemplatesChecklistListRoute
  NavbarLayoutAuditTemplatesChecklistIndexRoute: typeof NavbarLayoutAuditTemplatesChecklistIndexRoute
}

const NavbarLayoutAuditTemplatesChecklistRouteChildren: NavbarLayoutAuditTemplatesChecklistRouteChildren =
  {
    NavbarLayoutAuditTemplatesChecklistIdRoute:
      NavbarLayoutAuditTemplatesChecklistIdRoute,
    NavbarLayoutAuditTemplatesChecklistListRoute:
      NavbarLayoutAuditTemplatesChecklistListRoute,
    NavbarLayoutAuditTemplatesChecklistIndexRoute:
      NavbarLayoutAuditTemplatesChecklistIndexRoute,
  }

const NavbarLayoutAuditTemplatesChecklistRouteWithChildren =
  NavbarLayoutAuditTemplatesChecklistRoute._addFileChildren(
    NavbarLayoutAuditTemplatesChecklistRouteChildren,
  )

interface NavbarLayoutAuditTemplatesSelectRouteChildren {
  NavbarLayoutAuditTemplatesSelectIdRoute: typeof NavbarLayoutAuditTemplatesSelectIdRoute
  NavbarLayoutAuditTemplatesSelectListRoute: typeof NavbarLayoutAuditTemplatesSelectListRoute
  NavbarLayoutAuditTemplatesSelectIndexRoute: typeof NavbarLayoutAuditTemplatesSelectIndexRoute
}

const NavbarLayoutAuditTemplatesSelectRouteChildren: NavbarLayoutAuditTemplatesSelectRouteChildren =
  {
    NavbarLayoutAuditTemplatesSelectIdRoute:
      NavbarLayoutAuditTemplatesSelectIdRoute,
    NavbarLayoutAuditTemplatesSelectListRoute:
      NavbarLayoutAuditTemplatesSelectListRoute,
    NavbarLayoutAuditTemplatesSelectIndexRoute:
      NavbarLayoutAuditTemplatesSelectIndexRoute,
  }

const NavbarLayoutAuditTemplatesSelectRouteWithChildren =
  NavbarLayoutAuditTemplatesSelectRoute._addFileChildren(
    NavbarLayoutAuditTemplatesSelectRouteChildren,
  )

interface NavbarLayoutAuditTemplatesRouteChildren {
  NavbarLayoutAuditTemplatesChecklistRoute: typeof NavbarLayoutAuditTemplatesChecklistRouteWithChildren
  NavbarLayoutAuditTemplatesSelectRoute: typeof NavbarLayoutAuditTemplatesSelectRouteWithChildren
}

const NavbarLayoutAuditTemplatesRouteChildren: NavbarLayoutAuditTemplatesRouteChildren =
  {
    NavbarLayoutAuditTemplatesChecklistRoute:
      NavbarLayoutAuditTemplatesChecklistRouteWithChildren,
    NavbarLayoutAuditTemplatesSelectRoute:
      NavbarLayoutAuditTemplatesSelectRouteWithChildren,
  }

const NavbarLayoutAuditTemplatesRouteWithChildren =
  NavbarLayoutAuditTemplatesRoute._addFileChildren(
    NavbarLayoutAuditTemplatesRouteChildren,
  )

interface NavbarLayoutAuditRouteChildren {
  NavbarLayoutAuditChecklistRoute: typeof NavbarLayoutAuditChecklistRouteWithChildren
  NavbarLayoutAuditTemplatesRoute: typeof NavbarLayoutAuditTemplatesRouteWithChildren
  NavbarLayoutAuditIndexRoute: typeof NavbarLayoutAuditIndexRoute
}

const NavbarLayoutAuditRouteChildren: NavbarLayoutAuditRouteChildren = {
  NavbarLayoutAuditChecklistRoute: NavbarLayoutAuditChecklistRouteWithChildren,
  NavbarLayoutAuditTemplatesRoute: NavbarLayoutAuditTemplatesRouteWithChildren,
  NavbarLayoutAuditIndexRoute: NavbarLayoutAuditIndexRoute,
}

const NavbarLayoutAuditRouteWithChildren =
  NavbarLayoutAuditRoute._addFileChildren(NavbarLayoutAuditRouteChildren)

interface NavbarLayoutCycleCountRouteChildren {
  NavbarLayoutCycleCountListRoute: typeof NavbarLayoutCycleCountListRoute
  NavbarLayoutCycleCountIndexRoute: typeof NavbarLayoutCycleCountIndexRoute
  NavbarLayoutCycleCountEntryIdRoute: typeof NavbarLayoutCycleCountEntryIdRoute
}

const NavbarLayoutCycleCountRouteChildren: NavbarLayoutCycleCountRouteChildren =
  {
    NavbarLayoutCycleCountListRoute: NavbarLayoutCycleCountListRoute,
    NavbarLayoutCycleCountIndexRoute: NavbarLayoutCycleCountIndexRoute,
    NavbarLayoutCycleCountEntryIdRoute: NavbarLayoutCycleCountEntryIdRoute,
  }

const NavbarLayoutCycleCountRouteWithChildren =
  NavbarLayoutCycleCountRoute._addFileChildren(
    NavbarLayoutCycleCountRouteChildren,
  )

interface NavbarLayoutDailyReportsShiftWorksheetRouteChildren {
  NavbarLayoutDailyReportsShiftWorksheetWorksheetRoute: typeof NavbarLayoutDailyReportsShiftWorksheetWorksheetRoute
  NavbarLayoutDailyReportsShiftWorksheetCreateRoute: typeof NavbarLayoutDailyReportsShiftWorksheetCreateRoute
  NavbarLayoutDailyReportsShiftWorksheetIndexRoute: typeof NavbarLayoutDailyReportsShiftWorksheetIndexRoute
}

const NavbarLayoutDailyReportsShiftWorksheetRouteChildren: NavbarLayoutDailyReportsShiftWorksheetRouteChildren =
  {
    NavbarLayoutDailyReportsShiftWorksheetWorksheetRoute:
      NavbarLayoutDailyReportsShiftWorksheetWorksheetRoute,
    NavbarLayoutDailyReportsShiftWorksheetCreateRoute:
      NavbarLayoutDailyReportsShiftWorksheetCreateRoute,
    NavbarLayoutDailyReportsShiftWorksheetIndexRoute:
      NavbarLayoutDailyReportsShiftWorksheetIndexRoute,
  }

const NavbarLayoutDailyReportsShiftWorksheetRouteWithChildren =
  NavbarLayoutDailyReportsShiftWorksheetRoute._addFileChildren(
    NavbarLayoutDailyReportsShiftWorksheetRouteChildren,
  )

interface NavbarLayoutDailyReportsRouteChildren {
  NavbarLayoutDailyReportsCashSummaryRoute: typeof NavbarLayoutDailyReportsCashSummaryRoute
  NavbarLayoutDailyReportsShiftWorksheetRoute: typeof NavbarLayoutDailyReportsShiftWorksheetRouteWithChildren
}

const NavbarLayoutDailyReportsRouteChildren: NavbarLayoutDailyReportsRouteChildren =
  {
    NavbarLayoutDailyReportsCashSummaryRoute:
      NavbarLayoutDailyReportsCashSummaryRoute,
    NavbarLayoutDailyReportsShiftWorksheetRoute:
      NavbarLayoutDailyReportsShiftWorksheetRouteWithChildren,
  }

const NavbarLayoutDailyReportsRouteWithChildren =
  NavbarLayoutDailyReportsRoute._addFileChildren(
    NavbarLayoutDailyReportsRouteChildren,
  )

interface NavbarLayoutFleetRouteChildren {
  NavbarLayoutFleetListRoute: typeof NavbarLayoutFleetListRoute
  NavbarLayoutFleetIndexRoute: typeof NavbarLayoutFleetIndexRoute
}

const NavbarLayoutFleetRouteChildren: NavbarLayoutFleetRouteChildren = {
  NavbarLayoutFleetListRoute: NavbarLayoutFleetListRoute,
  NavbarLayoutFleetIndexRoute: NavbarLayoutFleetIndexRoute,
}

const NavbarLayoutFleetRouteWithChildren =
  NavbarLayoutFleetRoute._addFileChildren(NavbarLayoutFleetRouteChildren)

interface NavbarLayoutKardpollRouteChildren {
  NavbarLayoutKardpollListRoute: typeof NavbarLayoutKardpollListRoute
  NavbarLayoutKardpollIndexRoute: typeof NavbarLayoutKardpollIndexRoute
}

const NavbarLayoutKardpollRouteChildren: NavbarLayoutKardpollRouteChildren = {
  NavbarLayoutKardpollListRoute: NavbarLayoutKardpollListRoute,
  NavbarLayoutKardpollIndexRoute: NavbarLayoutKardpollIndexRoute,
}

const NavbarLayoutKardpollRouteWithChildren =
  NavbarLayoutKardpollRoute._addFileChildren(NavbarLayoutKardpollRouteChildren)

interface NavbarLayoutOrderRecRouteChildren {
  NavbarLayoutOrderRecIdRoute: typeof NavbarLayoutOrderRecIdRoute
  NavbarLayoutOrderRecDashboardRoute: typeof NavbarLayoutOrderRecDashboardRoute
  NavbarLayoutOrderRecListRoute: typeof NavbarLayoutOrderRecListRoute
  NavbarLayoutOrderRecIndexRoute: typeof NavbarLayoutOrderRecIndexRoute
}

const NavbarLayoutOrderRecRouteChildren: NavbarLayoutOrderRecRouteChildren = {
  NavbarLayoutOrderRecIdRoute: NavbarLayoutOrderRecIdRoute,
  NavbarLayoutOrderRecDashboardRoute: NavbarLayoutOrderRecDashboardRoute,
  NavbarLayoutOrderRecListRoute: NavbarLayoutOrderRecListRoute,
  NavbarLayoutOrderRecIndexRoute: NavbarLayoutOrderRecIndexRoute,
}

const NavbarLayoutOrderRecRouteWithChildren =
  NavbarLayoutOrderRecRoute._addFileChildren(NavbarLayoutOrderRecRouteChildren)

interface NavbarLayoutPayablesRouteChildren {
  NavbarLayoutPayablesImagesRoute: typeof NavbarLayoutPayablesImagesRoute
  NavbarLayoutPayablesListRoute: typeof NavbarLayoutPayablesListRoute
  NavbarLayoutPayablesReviewRoute: typeof NavbarLayoutPayablesReviewRoute
  NavbarLayoutPayablesIndexRoute: typeof NavbarLayoutPayablesIndexRoute
}

const NavbarLayoutPayablesRouteChildren: NavbarLayoutPayablesRouteChildren = {
  NavbarLayoutPayablesImagesRoute: NavbarLayoutPayablesImagesRoute,
  NavbarLayoutPayablesListRoute: NavbarLayoutPayablesListRoute,
  NavbarLayoutPayablesReviewRoute: NavbarLayoutPayablesReviewRoute,
  NavbarLayoutPayablesIndexRoute: NavbarLayoutPayablesIndexRoute,
}

const NavbarLayoutPayablesRouteWithChildren =
  NavbarLayoutPayablesRoute._addFileChildren(NavbarLayoutPayablesRouteChildren)

interface NavbarLayoutPoRouteChildren {
  NavbarLayoutPoListRoute: typeof NavbarLayoutPoListRoute
  NavbarLayoutPoReceiptRoute: typeof NavbarLayoutPoReceiptRoute
  NavbarLayoutPoSignatureRoute: typeof NavbarLayoutPoSignatureRoute
  NavbarLayoutPoIndexRoute: typeof NavbarLayoutPoIndexRoute
}

const NavbarLayoutPoRouteChildren: NavbarLayoutPoRouteChildren = {
  NavbarLayoutPoListRoute: NavbarLayoutPoListRoute,
  NavbarLayoutPoReceiptRoute: NavbarLayoutPoReceiptRoute,
  NavbarLayoutPoSignatureRoute: NavbarLayoutPoSignatureRoute,
  NavbarLayoutPoIndexRoute: NavbarLayoutPoIndexRoute,
}

const NavbarLayoutPoRouteWithChildren = NavbarLayoutPoRoute._addFileChildren(
  NavbarLayoutPoRouteChildren,
)

interface NavbarLayoutReportsSalesSummaryRouteChildren {
  NavbarLayoutReportsSalesSummaryUploadRoute: typeof NavbarLayoutReportsSalesSummaryUploadRoute
  NavbarLayoutReportsSalesSummaryIndexRoute: typeof NavbarLayoutReportsSalesSummaryIndexRoute
}

const NavbarLayoutReportsSalesSummaryRouteChildren: NavbarLayoutReportsSalesSummaryRouteChildren =
  {
    NavbarLayoutReportsSalesSummaryUploadRoute:
      NavbarLayoutReportsSalesSummaryUploadRoute,
    NavbarLayoutReportsSalesSummaryIndexRoute:
      NavbarLayoutReportsSalesSummaryIndexRoute,
  }

const NavbarLayoutReportsSalesSummaryRouteWithChildren =
  NavbarLayoutReportsSalesSummaryRoute._addFileChildren(
    NavbarLayoutReportsSalesSummaryRouteChildren,
  )

interface NavbarLayoutReportsRouteChildren {
  NavbarLayoutReportsOtherRoute: typeof NavbarLayoutReportsOtherRoute
  NavbarLayoutReportsSalesSummaryRoute: typeof NavbarLayoutReportsSalesSummaryRouteWithChildren
}

const NavbarLayoutReportsRouteChildren: NavbarLayoutReportsRouteChildren = {
  NavbarLayoutReportsOtherRoute: NavbarLayoutReportsOtherRoute,
  NavbarLayoutReportsSalesSummaryRoute:
    NavbarLayoutReportsSalesSummaryRouteWithChildren,
}

const NavbarLayoutReportsRouteWithChildren =
  NavbarLayoutReportsRoute._addFileChildren(NavbarLayoutReportsRouteChildren)

interface NavbarLayoutSettingsPaypointsRouteChildren {
  NavbarLayoutSettingsPaypointsSiteRoute: typeof NavbarLayoutSettingsPaypointsSiteRoute
  NavbarLayoutSettingsPaypointsIndexRoute: typeof NavbarLayoutSettingsPaypointsIndexRoute
}

const NavbarLayoutSettingsPaypointsRouteChildren: NavbarLayoutSettingsPaypointsRouteChildren =
  {
    NavbarLayoutSettingsPaypointsSiteRoute:
      NavbarLayoutSettingsPaypointsSiteRoute,
    NavbarLayoutSettingsPaypointsIndexRoute:
      NavbarLayoutSettingsPaypointsIndexRoute,
  }

const NavbarLayoutSettingsPaypointsRouteWithChildren =
  NavbarLayoutSettingsPaypointsRoute._addFileChildren(
    NavbarLayoutSettingsPaypointsRouteChildren,
  )

interface NavbarLayoutSettingsUsersRouteChildren {
  NavbarLayoutSettingsUsersUserIdRoute: typeof NavbarLayoutSettingsUsersUserIdRoute
  NavbarLayoutSettingsUsersIndexRoute: typeof NavbarLayoutSettingsUsersIndexRoute
}

const NavbarLayoutSettingsUsersRouteChildren: NavbarLayoutSettingsUsersRouteChildren =
  {
    NavbarLayoutSettingsUsersUserIdRoute: NavbarLayoutSettingsUsersUserIdRoute,
    NavbarLayoutSettingsUsersIndexRoute: NavbarLayoutSettingsUsersIndexRoute,
  }

const NavbarLayoutSettingsUsersRouteWithChildren =
  NavbarLayoutSettingsUsersRoute._addFileChildren(
    NavbarLayoutSettingsUsersRouteChildren,
  )

interface NavbarLayoutSettingsRouteChildren {
  NavbarLayoutSettingsPaypointsRoute: typeof NavbarLayoutSettingsPaypointsRouteWithChildren
  NavbarLayoutSettingsUsersRoute: typeof NavbarLayoutSettingsUsersRouteWithChildren
  NavbarLayoutSettingsIndexRoute: typeof NavbarLayoutSettingsIndexRoute
  NavbarLayoutSettingsPermissionsIndexRoute: typeof NavbarLayoutSettingsPermissionsIndexRoute
}

const NavbarLayoutSettingsRouteChildren: NavbarLayoutSettingsRouteChildren = {
  NavbarLayoutSettingsPaypointsRoute:
    NavbarLayoutSettingsPaypointsRouteWithChildren,
  NavbarLayoutSettingsUsersRoute: NavbarLayoutSettingsUsersRouteWithChildren,
  NavbarLayoutSettingsIndexRoute: NavbarLayoutSettingsIndexRoute,
  NavbarLayoutSettingsPermissionsIndexRoute:
    NavbarLayoutSettingsPermissionsIndexRoute,
}

const NavbarLayoutSettingsRouteWithChildren =
  NavbarLayoutSettingsRoute._addFileChildren(NavbarLayoutSettingsRouteChildren)

interface NavbarLayoutStatusRouteChildren {
  NavbarLayoutStatusListRoute: typeof NavbarLayoutStatusListRoute
  NavbarLayoutStatusIndexRoute: typeof NavbarLayoutStatusIndexRoute
}

const NavbarLayoutStatusRouteChildren: NavbarLayoutStatusRouteChildren = {
  NavbarLayoutStatusListRoute: NavbarLayoutStatusListRoute,
  NavbarLayoutStatusIndexRoute: NavbarLayoutStatusIndexRoute,
}

const NavbarLayoutStatusRouteWithChildren =
  NavbarLayoutStatusRoute._addFileChildren(NavbarLayoutStatusRouteChildren)

interface NavbarLayoutVendorRouteChildren {
  NavbarLayoutVendorListRoute: typeof NavbarLayoutVendorListRoute
  NavbarLayoutVendorIndexRoute: typeof NavbarLayoutVendorIndexRoute
  NavbarLayoutVendorEditIdRoute: typeof NavbarLayoutVendorEditIdRoute
}

const NavbarLayoutVendorRouteChildren: NavbarLayoutVendorRouteChildren = {
  NavbarLayoutVendorListRoute: NavbarLayoutVendorListRoute,
  NavbarLayoutVendorIndexRoute: NavbarLayoutVendorIndexRoute,
  NavbarLayoutVendorEditIdRoute: NavbarLayoutVendorEditIdRoute,
}

const NavbarLayoutVendorRouteWithChildren =
  NavbarLayoutVendorRoute._addFileChildren(NavbarLayoutVendorRouteChildren)

interface NavbarLayoutRouteChildren {
  NavbarLayoutAuditRoute: typeof NavbarLayoutAuditRouteWithChildren
  NavbarLayoutCycleCountRoute: typeof NavbarLayoutCycleCountRouteWithChildren
  NavbarLayoutDailyReportsRoute: typeof NavbarLayoutDailyReportsRouteWithChildren
  NavbarLayoutFleetRoute: typeof NavbarLayoutFleetRouteWithChildren
  NavbarLayoutKardpollRoute: typeof NavbarLayoutKardpollRouteWithChildren
  NavbarLayoutOrderRecRoute: typeof NavbarLayoutOrderRecRouteWithChildren
  NavbarLayoutPayablesRoute: typeof NavbarLayoutPayablesRouteWithChildren
  NavbarLayoutPoRoute: typeof NavbarLayoutPoRouteWithChildren
  NavbarLayoutReportsRoute: typeof NavbarLayoutReportsRouteWithChildren
  NavbarLayoutSettingsRoute: typeof NavbarLayoutSettingsRouteWithChildren
  NavbarLayoutStatusRoute: typeof NavbarLayoutStatusRouteWithChildren
  NavbarLayoutVendorRoute: typeof NavbarLayoutVendorRouteWithChildren
  NavbarLayoutIndexRoute: typeof NavbarLayoutIndexRoute
}

const NavbarLayoutRouteChildren: NavbarLayoutRouteChildren = {
  NavbarLayoutAuditRoute: NavbarLayoutAuditRouteWithChildren,
  NavbarLayoutCycleCountRoute: NavbarLayoutCycleCountRouteWithChildren,
  NavbarLayoutDailyReportsRoute: NavbarLayoutDailyReportsRouteWithChildren,
  NavbarLayoutFleetRoute: NavbarLayoutFleetRouteWithChildren,
  NavbarLayoutKardpollRoute: NavbarLayoutKardpollRouteWithChildren,
  NavbarLayoutOrderRecRoute: NavbarLayoutOrderRecRouteWithChildren,
  NavbarLayoutPayablesRoute: NavbarLayoutPayablesRouteWithChildren,
  NavbarLayoutPoRoute: NavbarLayoutPoRouteWithChildren,
  NavbarLayoutReportsRoute: NavbarLayoutReportsRouteWithChildren,
  NavbarLayoutSettingsRoute: NavbarLayoutSettingsRouteWithChildren,
  NavbarLayoutStatusRoute: NavbarLayoutStatusRouteWithChildren,
  NavbarLayoutVendorRoute: NavbarLayoutVendorRouteWithChildren,
  NavbarLayoutIndexRoute: NavbarLayoutIndexRoute,
}

const NavbarLayoutRouteWithChildren = NavbarLayoutRoute._addFileChildren(
  NavbarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  NavbarLayoutRoute: NavbarLayoutRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
