name: Test SSH Connection

on:
  workflow_dispatch:  # allows manual trigger in GitHub Actions

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "SSH connection successful!"
            whoami
            pwd
